/* eslint-disable quote-props,comma-dangle,@typescript-eslint/ban-types */
import Entity from '../../../types/Entity';
import {ServiceConfig} from '../types';

// DO NOT EDIT! THIS IS GENERATED FILE

const config: ServiceConfig = {
  idType: 'int',
  autogeneratedStringId: false,
  auditable: true,
  withSearch: true,
  externalSearch: false,
  dateFields: [
    'matchDate'
  ],
  otherFields: [
    'id',
    'createdByManagerId',
    'lastChangedByManagerId',
    'title',
    'competitionId',
    'firstTeamId',
    'firstTeamColor',
    'firstTeamOnFieldId',
    'secondTeamId',
    'secondTeamColor',
    'matchTime',
    'duration',
    'place',
    'firstTeamPoints',
    'secondTeamPoints',
    'redCardFirstTeam',
    'redCardSecondTeam',
    'yellowCardFirstTeam',
    'yellowCardSecondTeam',
    'firstTeamHandleTime',
    'secondTeamHandleTime',
    'linkToProtocol',
    'matchStatusId'
  ],
  forbiddenForUserFields: [
    'createdByManagerId',
    'lastChangedByManagerId'
  ],
  entityTypeId: Entity.Match,
};

export default config;
