/* eslint-disable quote-props,comma-dangle,@typescript-eslint/ban-types */
import {ServiceConfig} from '../types';

// DO NOT EDIT! THIS IS GENERATED FILE

const config: ServiceConfig = {
  idType: 'string',
  autogeneratedStringId: false,
  auditable: true,
  withSearch: true,
  externalSearch: false,
  dateFields: [
    'version'
  ],
  otherFields: [
    'id',
    'title',
    'originalEntityType',
    'generatingEntityType',
    'originalEntityFilter',
    'generatingEntityConstructionRules'
  ],
  forbiddenForUserFields: [],
  entityTypeId: 'autogenerationRule',
};

export default config;
