/* eslint-disable quote-props,comma-dangle,@typescript-eslint/ban-types */
import Entity from '../../../types/Entity';
import {InfoRegistryConfig} from '../types';

// DO NOT EDIT! THIS IS GENERATED FILE

const config: InfoRegistryConfig = {
  idType: 'int',
  autogeneratedStringId: false,
  auditable: true,
  withSearch: false,
  externalSearch: false,
  dateFields: [
    'lastAggregatesComputed',
    'lastAggregatesScheduled',
    'lastEntityUpdate'
  ],
  otherFields: [
    'id',
    'entityTypeId',
    'entityId',
    'aggregateVersion'
  ],
  forbiddenForUserFields: [],
  entityTypeId: Entity.AggregateTracking,
  period: 'notPeriodic',
};

export default config;
