
{{ if .Values.fluentd.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |

    <filter **>
       @type parser
       key_name log
       reserve_data true
       <parse>
         @type multi_format
         types upstream_status:string
         <pattern>
           format json
           time_format %d/%b/%Y:%H:%M:%S %z
         </pattern>
         <pattern>
           format none
         </pattern>
       </parse>
    </filter>

    <filter **>
      @type record_transformer
      remove_keys container_info,$.docker.container_id,$.kubernetes.namespace_labels.field_cattle_io/projectId,$.kubernetes.namespace_labels.kubernetes_io/metadata_name,$.kubernetes.pod_id,$.kubernetes.pod_ip, log
    </filter>

    <match **>
       @type elasticsearch
       host "#{ENV['elk_host']}"
       port "#{ENV['elk_port']}"
       user "#{ENV['elk_user']}"
       password "#{ENV['elk_password']}"
       scheme "https"
       ssl_verify "false"
       ssl_version TLSv1_2
       log_es_400_reason true
       logstash_format true
       reload_connections "true"
       logstash_prefix "{{ $.Values.global.projectName }}-{{ $.Values.global.env }}-logs-{{ $.Values.global.clusterName }}"
       buffer_chunk_limit 1M
       buffer_queue_limit 32
       flush_interval 10s
       max_retry_wait 30
       disable_retry_limit
       num_threads 2
    </match>
{{ end }}

