/* eslint-disable quote-props,comma-dangle,@typescript-eslint/ban-types */
import {ServiceConfig} from '../types';

// DO NOT EDIT! THIS IS GENERATED FILE

const config: ServiceConfig = {
  idType: 'int',
  autogeneratedStringId: false,
  auditable: true,
  withSearch: true,
  externalSearch: false,
  dateFields: [
    'dateCreated',
    'dateSent'
  ],
  otherFields: [
    'id',
    'mailingCampaignId',
    'templateId',
    'languageId',
    'to',
    'locals',
    'localsHash',
    'priority',
    'error',
    'html',
    'text',
    'uniqueKey',
    'subject',
    'mailingMessageStatusId',
    'messageTemplateLangVariantId'
  ],
  forbiddenForUserFields: [],
  entityTypeId: 'mailingMessage',
};

export default config;
