/* eslint-disable quote-props,comma-dangle,@typescript-eslint/ban-types */
import Entity from '../../../types/Entity';
import {ServiceConfig} from '../types';

// DO NOT EDIT! THIS IS GENERATED FILE

const config: ServiceConfig = {
  idType: 'int',
  autogeneratedStringId: false,
  auditable: false,
  withSearch: true,
  externalSearch: false,
  dateFields: [
    'date'
  ],
  otherFields: [
    'id',
    'title',
    'error',
    'entityTypeId',
    'entityId',
    'actionTypeId',
    'managerId',
    'userId',
    'foreignEntityType',
    'foreignEntityId',
    'actionData'
  ],
  forbiddenForUserFields: [],
  entityTypeId: Entity.AuditLog,
};

export default config;
