/* eslint-disable quote-props,comma-dangle,@typescript-eslint/ban-types */
import Entity from '../../../types/Entity';
import {DocumentConfig} from '../types';

// DO NOT EDIT! THIS IS GENERATED FILE

const config: DocumentConfig = {
  idType: 'int',
  autogeneratedStringId: false,
  auditable: true,
  withSearch: true,
  externalSearch: false,
  dateFields: [
    'date'
  ],
  otherFields: [
    'id',
    'timeSecond',
    'linkToTimeSecond',
    'startControversialPoint',
    'startHighlight',
    'order',
    'eventTypeId',
    'videoId',
    'teamForCompetitionId',
    'mainPlayerId',
    'secondPlayerId',
    'firstPlayerRoleId',
    'secondPlayerRoleId',
    'periodTypeId',
    'matchId',
    'points',
    'periodNumber'
  ],
  forbiddenForUserFields: [],
  entityTypeId: Entity.Event,
  registries: [],
  registrarDependedRegistries: [],
};

export default config;
