// DO NOT EDIT! THIS IS GENERATED FILE

enum Entity {
  AdmRefreshToken = 'admRefreshToken',
  AggregateTracking = 'aggregateTracking',
  AppLogin = 'appLogin',
  AppRefreshToken = 'appRefreshToken',
  AuditLogActionType = 'auditLogActionType',
  AuditLog = 'auditLog',
  AutogenerationHistoryEntry = 'autogenerationHistoryEntry',
  AutogenerationRule = 'autogenerationRule',
  Delegation = 'delegation',
  Entity = 'entity',
  File = 'file',
  Language = 'language',
  MailingCampaign = 'mailingCampaign',
  MailingMessageStatus = 'mailingMessageStatus',
  MailingMessage = 'mailingMessage',
  MailingType = 'mailingType',
  ManagerLogin = 'managerLogin',
  Manager = 'manager',
  ManagersToPermission = 'managersToPermission',
  ManagersToRole = 'managersToRole',
  MessageTemplateLangVariant = 'messageTemplateLangVariant',
  MessageTemplate = 'messageTemplate',
  MessageType = 'messageType',
  Permission = 'permission',
  Role = 'role',
  RolesToPermission = 'rolesToPermission',
  Stat = 'stat',
  Tag = 'tag',
  TemplateStyle = 'templateStyle',
  Tenant = 'tenant',
  Unit = 'unit',
  User = 'user',
}

export default Entity;
