/* eslint-disable quote-props,comma-dangle,@typescript-eslint/ban-types */
import Entity from '../../../types/Entity';
import {ServiceConfig} from '../types';

// DO NOT EDIT! THIS IS GENERATED FILE

const config: ServiceConfig = {
  idType: 'int',
  autogeneratedStringId: false,
  auditable: true,
  withSearch: true,
  externalSearch: false,
  dateFields: [],
  otherFields: [
    'id',
    'originalName',
    'url',
    'mimetype',
    's3Key',
    'eTag',
    'bytes'
  ],
  forbiddenForUserFields: [],
  entityTypeId: Entity.File,
};

export default config;
