version: "3.9"
services:
# postgres
  postgres:
    image: "postgres"
    ports:
      - "5432:5432/tcp"
    expose:
      - "5432/tcp"
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./keycloak/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
  # keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    volumes:
      - type: bind
        source: ./keycloak/init.json
        target: /init.json
        read_only: true
    ports:
      - "8180:8180"
    command:
      - "-Djboss.socket.binding.port-offset=100"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=singleFile"
      - "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
      - "-Dkeycloak.migration.file=/init.json"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      DB_SCHEMA: keycloak_schema
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_HOSTNAME: localhost
      KEYCLOAK_FRONTEND_URL: http://localhost:8180/auth
    depends_on:
      - postgres
    restart: unless-stopped
# minio
  minio:
    image: "minio/minio"
    ports:
      - "9000:9000/tcp"
      - "9001:9001/tcp"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data
    restart: unless-stopped
  mailhog:
    image: "mailhog/mailhog"
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped
# launching all containers
  starter:
    image: alpine
    entrypoint: >
      /bin/sh -c 'echo "    /\\___/\\
         /       \\
        l  ^   ^  l
      --l----*----l--
         \\   w   /     - Meow! All containers have been successfully launched! Time to have fun dancing cha-cha-cha!
          ======
         /       \\ __
         l        l\\ \\
         l        l/ /
         l  l l   l /
         \\ ml lm /_/"'
    pull_policy: always
    depends_on:
      - minio
      - postgres
      - keycloak
      - mailhog
# local data storage
volumes:
  postgres-data:
  minio-data:
