/* eslint-disable quote-props,comma-dangle,@typescript-eslint/ban-types */
import Entity from '../../../types/Entity';
import {ServiceConfig} from '../types';

// DO NOT EDIT! THIS IS GENERATED FILE

const config: ServiceConfig = {
  idType: 'int',
  autogeneratedStringId: false,
  auditable: true,
  withSearch: true,
  externalSearch: false,
  dateFields: [
    'dateOfBirth'
  ],
  otherFields: [
    'id',
    'firstname',
    'lastname',
    'patronymic',
    'title',
    'playerName',
    'number',
    'age',
    'teamId',
    'createdByManagerId',
    'lastChangedByManagerId',
    'parentId',
    'linkToProfile',
    'playerRating',
    'photoId',
    'playerRatingAverage',
    'commonPlayerRatingGoalkeeper',
    'commonPlayerRatingAttack',
    'commonPlayerRatingMidfielder',
    'commonPlayerRatingDefender',
    'playedMatches',
    'averagePlayerRatingGoalkeeper',
    'averagePlayerRatingAttack',
    'averagePlayerRatingMidfielder',
    'averagePlayerRatingDefender',
    'playerAggregatedRoleId',
    'playerTag',
    'progressivePassAccuracy',
    'playerRankId'
  ],
  forbiddenForUserFields: [
    'title',
    'playerName',
    'createdByManagerId',
    'lastChangedByManagerId'
  ],
  entityTypeId: Entity.Player,
};

export default config;
