import {AdditionalAdmRefreshTokensService} from './AdmRefreshTokensService/AdditionalAdmRefreshTokensService';
import {AdditionalAggregateTrackingsService} from './AggregateTrackingsService/AdditionalAggregateTrackingsService';
import {AdditionalAppLoginsService} from './AppLoginsService/AdditionalAppLoginsService';
import {AdditionalAppRefreshTokensService} from './AppRefreshTokensService/AdditionalAppRefreshTokensService';
import {AdditionalAuditLogActionTypesService} from './AuditLogActionTypesService/AdditionalAuditLogActionTypesService';
import {AdditionalAuditLogsService} from './AuditLogsService/AdditionalAuditLogsService';
import {AdditionalAutogenerationHistoryEntriesService} from './AutogenerationHistoryEntriesService/AdditionalAutogenerationHistoryEntriesService';
import {AdditionalAutogenerationRulesService} from './AutogenerationRulesService/AdditionalAutogenerationRulesService';
import {AdditionalConfigurationVariablesService} from './ConfigurationVariablesService/AdditionalConfigurationVariablesService';
import {AdditionalDelegationsService} from './DelegationsService/AdditionalDelegationsService';
import {AdditionalEntitiesService} from './EntitiesService/AdditionalEntitiesService';
import {AdditionalFilesService} from './FilesService/AdditionalFilesService';
import {AdditionalLanguagesService} from './LanguagesService/AdditionalLanguagesService';
import {AdditionalMailingCampaignStatusesService} from './MailingCampaignStatusesService/AdditionalMailingCampaignStatusesService';
import {AdditionalMailingCampaignsService} from './MailingCampaignsService/AdditionalMailingCampaignsService';
import {AdditionalMailingMessageStatusesService} from './MailingMessageStatusesService/AdditionalMailingMessageStatusesService';
import {AdditionalMailingMessagesService} from './MailingMessagesService/AdditionalMailingMessagesService';
import {AdditionalMailingTypesService} from './MailingTypesService/AdditionalMailingTypesService';
import {AdditionalManagerLoginsService} from './ManagerLoginsService/AdditionalManagerLoginsService';
import {AdditionalManagersService} from './ManagersService/AdditionalManagersService';
import {AdditionalManagersToPermissionsService} from './ManagersToPermissionsService/AdditionalManagersToPermissionsService';
import {AdditionalManagersToRolesService} from './ManagersToRolesService/AdditionalManagersToRolesService';
import {AdditionalMessageTemplateLangVariantsService} from './MessageTemplateLangVariantsService/AdditionalMessageTemplateLangVariantsService';
import {AdditionalMessageTemplatesService} from './MessageTemplatesService/AdditionalMessageTemplatesService';
import {AdditionalMessageTypesService} from './MessageTypesService/AdditionalMessageTypesService';
import {AdditionalPermissionsService} from './PermissionsService/AdditionalPermissionsService';
import {AdditionalRolesService} from './RolesService/AdditionalRolesService';
import {AdditionalRolesToPermissionsService} from './RolesToPermissionsService/AdditionalRolesToPermissionsService';
import {AdditionalStatsService} from './StatsService/AdditionalStatsService';
import {AdditionalTagsService} from './TagsService/AdditionalTagsService';
import {AdditionalTemplateStylesService} from './TemplateStylesService/AdditionalTemplateStylesService';
import {AdditionalTenantsService} from './TenantsService/AdditionalTenantsService';
import {AdditionalUnitsService} from './UnitsService/AdditionalUnitsService';
import {AdditionalUsersService} from './UsersService/AdditionalUsersService';
import {HelpService} from './HelpService/HelpService';

// DO NOT EDIT! THIS IS GENERATED FILE

export interface BaseServices {
  help: HelpService;
  admRefreshTokens: AdditionalAdmRefreshTokensService;
  aggregateTrackings: AdditionalAggregateTrackingsService;
  appLogins: AdditionalAppLoginsService;
  appRefreshTokens: AdditionalAppRefreshTokensService;
  auditLogActionTypes: AdditionalAuditLogActionTypesService;
  auditLogs: AdditionalAuditLogsService;
  autogenerationHistoryEntries: AdditionalAutogenerationHistoryEntriesService;
  autogenerationRules: AdditionalAutogenerationRulesService;
  configurationVariables: AdditionalConfigurationVariablesService;
  delegations: AdditionalDelegationsService;
  entities: AdditionalEntitiesService;
  files: AdditionalFilesService;
  languages: AdditionalLanguagesService;
  mailingCampaignStatuses: AdditionalMailingCampaignStatusesService;
  mailingCampaigns: AdditionalMailingCampaignsService;
  mailingMessageStatuses: AdditionalMailingMessageStatusesService;
  mailingMessages: AdditionalMailingMessagesService;
  mailingTypes: AdditionalMailingTypesService;
  managerLogins: AdditionalManagerLoginsService;
  managers: AdditionalManagersService;
  managersToPermissions: AdditionalManagersToPermissionsService;
  managersToRoles: AdditionalManagersToRolesService;
  messageTemplateLangVariants: AdditionalMessageTemplateLangVariantsService;
  messageTemplates: AdditionalMessageTemplatesService;
  messageTypes: AdditionalMessageTypesService;
  permissions: AdditionalPermissionsService;
  roles: AdditionalRolesService;
  rolesToPermissions: AdditionalRolesToPermissionsService;
  stats: AdditionalStatsService;
  tags: AdditionalTagsService;
  templateStyles: AdditionalTemplateStylesService;
  tenants: AdditionalTenantsService;
  units: AdditionalUnitsService;
  users: AdditionalUsersService;
}
