/* eslint-disable quote-props,comma-dangle,@typescript-eslint/ban-types */
import Entity from '../../../types/Entity';
import {ServiceConfig} from '../types';

// DO NOT EDIT! THIS IS GENERATED FILE

const config: ServiceConfig = {
  idType: 'int',
  autogeneratedStringId: false,
  auditable: true,
  withSearch: true,
  externalSearch: false,
  dateFields: [],
  otherFields: [
    'id',
    'title',
    'firstname',
    'lastname',
    'patronymic',
    'createdByManagerId',
    'lastChangedByManagerId'
  ],
  forbiddenForUserFields: [
    'title',
    'createdByManagerId',
    'lastChangedByManagerId'
  ],
  entityTypeId: Entity.Parent,
};

export default config;
