/* eslint-disable quote-props,comma-dangle,@typescript-eslint/ban-types */
import {ServiceConfig} from '../types';

// DO NOT EDIT! THIS IS GENERATED FILE

const config: ServiceConfig = {
  idType: 'string',
  autogeneratedStringId: false,
  auditable: true,
  withSearch: true,
  externalSearch: false,
  dateFields: [
    'updated'
  ],
  otherFields: [
    'id',
    'helloCount'
  ],
  forbiddenForUserFields: [],
  entityTypeId: 'stat',
};

export default config;
